spring:
  application:
    name: MSUser

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
    password: 'root'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/